# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSH2 Connect CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt install -y openssh-server && sudo systemctl start sshd
    - run: ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''
    - run: cat ~/.ssh/id_ed25519.pub > ~/.ssh/authorized_keys
    - run: yarn --frozen-lockfile
    - run: yarn run test
